-- NaijaFix chat foundation
-- Run in Supabase SQL Editor after naijafix_final_features.sql.
-- Idempotent: uses IF NOT EXISTS / ON CONFLICT guards.

-- A. Conversations
create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  booking_id bigint,
  customer_user_id uuid not null,
  provider_user_id uuid not null,
  customer_name text,
  provider_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.conversations enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'conversations'
      and policyname = 'Customers can view their own conversations'
  ) then
    create policy "Customers can view their own conversations"
      on public.conversations
      for select to authenticated
      using (customer_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'conversations'
      and policyname = 'Providers can view their own conversations'
  ) then
    create policy "Providers can view their own conversations"
      on public.conversations
      for select to authenticated
      using (provider_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'conversations'
      and policyname = 'Customers can create conversations as themselves'
  ) then
    create policy "Customers can create conversations as themselves"
      on public.conversations
      for insert to authenticated
      with check (customer_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'conversations'
      and policyname = 'Providers can create conversations as themselves'
  ) then
    create policy "Providers can create conversations as themselves"
      on public.conversations
      for insert to authenticated
      with check (provider_user_id = auth.uid());
  end if;
end
$$;

-- B. Messages
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null
    references public.conversations(id) on delete cascade,
  sender_user_id uuid not null,
  message_type text not null default 'text'
    check (message_type in ('text', 'image')),
  message_text text,
  attachment_path text,
  created_at timestamptz not null default now(),
  is_read boolean not null default false
);

alter table public.messages enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'messages'
      and policyname = 'Participants can view messages in their conversations'
  ) then
    create policy "Participants can view messages in their conversations"
      on public.messages
      for select to authenticated
      using (
        exists (
          select 1 from public.conversations c
          where c.id = conversation_id
            and (c.customer_user_id = auth.uid() or c.provider_user_id = auth.uid())
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'messages'
      and policyname = 'Participants can send messages in their conversations'
  ) then
    create policy "Participants can send messages in their conversations"
      on public.messages
      for insert to authenticated
      with check (
        sender_user_id = auth.uid()
        and exists (
          select 1 from public.conversations c
          where c.id = conversation_id
            and (c.customer_user_id = auth.uid() or c.provider_user_id = auth.uid())
        )
      );
  end if;
end
$$;

create index if not exists idx_messages_conversation
  on public.messages (conversation_id, created_at);

create index if not exists idx_conversations_participants
  on public.conversations (customer_user_id, provider_user_id);

-- C. Storage bucket for chat attachments (private)
insert into storage.buckets (id, name, public)
values ('chat-attachments', 'chat-attachments', false)
on conflict (id) do nothing;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Participants can upload chat attachments'
  ) then
    create policy "Participants can upload chat attachments"
      on storage.objects for insert to authenticated
      with check (
        bucket_id = 'chat-attachments'
        and exists (
          select 1 from public.conversations c
          where (storage.foldername(name))[1] = c.id::text
            and (c.customer_user_id = auth.uid() or c.provider_user_id = auth.uid())
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Participants can view chat attachments'
  ) then
    create policy "Participants can view chat attachments"
      on storage.objects for select to authenticated
      using (
        bucket_id = 'chat-attachments'
        and exists (
          select 1 from public.conversations c
          where (storage.foldername(name))[1] = c.id::text
            and (c.customer_user_id = auth.uid() or c.provider_user_id = auth.uid())
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Participants can delete chat attachments'
  ) then
    create policy "Participants can delete chat attachments"
      on storage.objects for delete to authenticated
      using (
        bucket_id = 'chat-attachments'
        and exists (
          select 1 from public.conversations c
          where (storage.foldername(name))[1] = c.id::text
            and (c.customer_user_id = auth.uid() or c.provider_user_id = auth.uid())
        )
      );
  end if;
end
$$;

-- D. Grants (RLS remains authoritative)
grant select, insert on public.conversations to authenticated;
grant select, insert on public.messages to authenticated;

-- E. Notification helper (consistent with existing RPC pattern)
create or replace function create_notification(
  p_user_id uuid,
  p_type text,
  p_title text,
  p_message text
)
returns void
language plpgsql
security definer
as $$
begin
  insert into public.notifications (user_id, type, title, message, is_read, created_at)
  values (p_user_id, p_type, p_title, p_message, false, now());
end;
$$;
