-- Notifications table and RLS policies
-- Run in Supabase SQL Editor.
-- Idempotent: safe to run multiple times.

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  type text not null default 'update',
  title text,
  message text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.notifications enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'notifications'
      and policyname = 'Users can view their own notifications'
  ) then
    create policy "Users can view their own notifications"
      on public.notifications
      for select to authenticated
      using (user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'notifications'
      and policyname = 'Users can update their own notifications'
  ) then
    create policy "Users can update their own notifications"
      on public.notifications
      for update to authenticated
      using (user_id = auth.uid())
      with check (user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'notifications'
      and policyname = 'Users can insert notifications via RPC only'
  ) then
    create policy "Users can insert notifications via RPC only"
      on public.notifications
      for insert to authenticated
      with check (user_id = auth.uid());
  end if;
end
$$;

grant select, insert, update on public.notifications to authenticated;

create index if not idx_notifications_user_read
  on public.notifications (user_id, is_read, created_at desc);
