-- Customer identity verification
-- Run in Supabase SQL Editor after naijafix_final_features.sql.
-- Idempotent: safe to run multiple times.

create table if not exists public.customer_verifications (
  id bigint generated by default as identity primary key,
  customer_user_id uuid not null,
  id_document_url text,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  submitted_at timestamptz not null default now(),
  resubmitted_at timestamptz,
  reviewed_at timestamptz,
  reviewed_by uuid,
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.customer_verifications enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'customer_verifications'
      and policyname = 'Customers can view their own verification'
  ) then
    create policy "Customers can view their own verification"
      on public.customer_verifications
      for select to authenticated
      using (customer_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'customer_verifications'
      and policyname = 'Customers can submit their own verification'
  ) then
    create policy "Customers can submit their own verification"
      on public.customer_verifications
      for insert to authenticated
      with check (customer_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'customer_verifications'
      and policyname = 'Customers can update their own verification'
  ) then
    create policy "Customers can update their own verification"
      on public.customer_verifications
      for update to authenticated
      using (customer_user_id = auth.uid())
      with check (customer_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'customer_verifications'
      and policyname = 'Admins can review customer verification'
  ) then
    create policy "Admins can review customer verification"
      on public.customer_verifications
      for all to authenticated
      using (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      )
      with check (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;
end
$$;

create index if not exists idx_customer_verifications_user
  on public.customer_verifications (customer_user_id);

insert into storage.buckets (id, name, public)
values ('customer-verification-documents', 'customer-verification-documents', false)
on conflict (id) do nothing;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Customers can upload their own ID documents'
  ) then
    create policy "Customers can upload their own ID documents"
      on storage.objects for insert to authenticated
      with check (
        bucket_id = 'customer-verification-documents'
        and (storage.foldername(name))[1] = auth.uid()::text
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Customers can view their own ID documents'
  ) then
    create policy "Customers can view their own ID documents"
      on storage.objects for select to authenticated
      using (
        bucket_id = 'customer-verification-documents'
        and (storage.foldername(name))[1] = auth.uid()::text
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Admins can review customer ID documents'
  ) then
    create policy "Admins can review customer ID documents"
      on storage.objects for select to authenticated
      using (
        bucket_id = 'customer-verification-documents'
        and exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Admins can delete customer ID documents'
  ) then
    create policy "Admins can delete customer ID documents"
      on storage.objects for delete to authenticated
      using (
        bucket_id = 'customer-verification-documents'
        and exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;
end
$$;

grant select, insert, update on public.customer_verifications to authenticated;
