-- NaijaFix marketplace extensions
-- Run in Supabase SQL Editor after all existing migrations.
-- Idempotent: safe to run multiple times.

-- ============================================================
-- A. Reviews / Ratings
-- ============================================================
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  booking_id bigint not null unique,
  customer_user_id uuid not null,
  provider_user_id uuid not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text,
  provider_response text,
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.reviews enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'reviews'
      and policyname = 'Customers can view reviews'
  ) then
    create policy "Customers can view reviews"
      on public.reviews
      for select to authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'reviews'
      and policyname = 'Customers can insert their own reviews'
  ) then
    create policy "Customers can insert their own reviews"
      on public.reviews
      for insert to authenticated
      with check (customer_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'reviews'
      and policyname = 'Customers can update their own reviews'
  ) then
    create policy "Customers can update their own reviews"
      on public.reviews
      for update to authenticated
      using (customer_user_id = auth.uid())
      with check (customer_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'reviews'
      and policyname = 'Providers can respond to their reviews'
  ) then
    create policy "Providers can respond to their reviews"
      on public.reviews
      for update to authenticated
      using (provider_user_id = auth.uid())
      with check (provider_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'reviews'
      and policyname = 'Admins can manage reviews'
  ) then
    create policy "Admins can manage reviews"
      on public.reviews
      for all to authenticated
      using (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      )
      with check (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;
end
$$;

create index if not exists idx_reviews_provider
  on public.reviews (provider_user_id, created_at desc);

create index if not exists idx_reviews_booking
  on public.reviews (booking_id);

-- ============================================================
-- B. Favorites
-- ============================================================
create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  customer_user_id uuid not null,
  provider_user_id uuid not null,
  created_at timestamptz not null default now(),
  unique (customer_user_id, provider_user_id)
);

alter table public.favorites enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'favorites'
      and policyname = 'Customers can view their own favorites'
  ) then
    create policy "Customers can view their own favorites"
      on public.favorites
      for select to authenticated
      using (customer_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'favorites'
      and policyname = 'Customers can manage their own favorites'
  ) then
    create policy "Customers can manage their own favorites"
      on public.favorites
      for all to authenticated
      using (customer_user_id = auth.uid())
      with check (customer_user_id = auth.uid());
  end if;
end
$$;

create index if not exists idx_favorites_customer
  on public.favorites (customer_user_id, created_at desc);

-- ============================================================
-- C. Provider Availability
-- ============================================================
create table if not exists public.provider_availability (
  id bigint generated by default as identity primary key,
  provider_user_id uuid not null,
  day_of_week integer not null check (day_of_week between 0 and 6),
  start_time time,
  end_time time,
  is_available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider_user_id, day_of_week)
);

alter table public.provider_availability enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'provider_availability'
      and policyname = 'Providers can manage their own availability'
  ) then
    create policy "Providers can manage their own availability"
      on public.provider_availability
      for all to authenticated
      using (provider_user_id = auth.uid())
      with check (provider_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'provider_availability'
      and policyname = 'Anyone can view provider availability'
  ) then
    create policy "Anyone can view provider availability"
      on public.provider_availability
      for select to authenticated
      using (true);
  end if;
end
$$;

create index if not exists idx_provider_availability_user
  on public.provider_availability (provider_user_id);

-- ============================================================
-- D. Quotes / Packages
-- ============================================================
create table if not exists public.service_packages (
  id bigint generated by default as identity primary key,
  provider_user_id uuid not null,
  name text not null,
  description text,
  price numeric(12, 2) not null,
  estimated_duration text,
  included_services text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.service_packages enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'service_packages'
      and policyname = 'Providers can manage their own packages'
  ) then
    create policy "Providers can manage their own packages"
      on public.service_packages
      for all to authenticated
      using (provider_user_id = auth.uid())
      with check (provider_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'service_packages'
      and policyname = 'Anyone can view service packages'
  ) then
    create policy "Anyone can view service packages"
      on public.service_packages
      for select to authenticated
      using (true);
  end if;
end
$$;

create index if not exists idx_service_packages_provider
  on public.service_packages (provider_user_id);

create table if not exists public.quotes (
  id bigint generated by default as identity primary key,
  booking_id bigint not null,
  provider_user_id uuid not null,
  amount numeric(12, 2) not null,
  description text not null,
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'declined', 'expired')),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.quotes enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'quotes'
      and policyname = 'Booking participants can view quotes'
  ) then
    create policy "Booking participants can view quotes"
      on public.quotes
      for select to authenticated
      using (
        exists (
          select 1 from public.bookings b
          where b.id = booking_id
            and (b.customer_user_id = auth.uid() or b.provider_user_id = auth.uid())
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'quotes'
      and policyname = 'Providers can create quotes'
  ) then
    create policy "Providers can create quotes"
      on public.quotes
      for insert to authenticated
      with check (provider_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'quotes'
      and policyname = 'Providers can update their own quotes'
  ) then
    create policy "Providers can update their own quotes"
      on public.quotes
      for update to authenticated
      using (provider_user_id = auth.uid())
      with check (provider_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'quotes'
      and policyname = 'Customers can accept or decline quotes'
  ) then
    create policy "Customers can accept or decline quotes"
      on public.quotes
      for update to authenticated
      using (
        exists (
          select 1 from public.bookings b
          where b.id = booking_id and b.customer_user_id = auth.uid()
        )
      )
      with check (
        exists (
          select 1 from public.bookings b
          where b.id = booking_id and b.customer_user_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'quotes'
      and policyname = 'Admins can manage quotes'
  ) then
    create policy "Admins can manage quotes"
      on public.quotes
      for all to authenticated
      using (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      )
      with check (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;
end
$$;

create index if not exists idx_quotes_booking
  on public.quotes (booking_id);

-- ============================================================
-- E. Booking Photos
-- ============================================================
create table if not exists public.booking_photos (
  id bigint generated by default as identity primary key,
  booking_id bigint not null,
  uploader_user_id uuid not null,
  file_path text not null,
  caption text,
  created_at timestamptz not null default now()
);

alter table public.booking_photos enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'booking_photos'
      and policyname = 'Booking participants can view booking photos'
  ) then
    create policy "Booking participants can view booking photos"
      on public.booking_photos
      for select to authenticated
      using (
        exists (
          select 1 from public.bookings b
          where b.id = booking_id
            and (b.customer_user_id = auth.uid() or b.provider_user_id = auth.uid())
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'booking_photos'
      and policyname = 'Booking participants can upload booking photos'
  ) then
    create policy "Booking participants can upload booking photos"
      on public.booking_photos
      for insert to authenticated
      with check (
        uploader_user_id = auth.uid()
        and exists (
          select 1 from public.bookings b
          where b.id = booking_id
            and (b.customer_user_id = auth.uid() or b.provider_user_id = auth.uid())
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'booking_photos'
      and policyname = 'Uploaders can delete their booking photos'
  ) then
    create policy "Uploaders can delete their booking photos"
      on public.booking_photos
      for delete to authenticated
      using (uploader_user_id = auth.uid());
  end if;
end
$$;

create index if not exists idx_booking_photos_booking
  on public.booking_photos (booking_id);

-- ============================================================
-- F. Provider emergency availability flag
-- ============================================================
alter table public.providers
  add column if not exists emergency_available boolean not null default false;

-- ============================================================
-- G. Booking lifecycle helpers
-- ============================================================
alter table public.bookings
  add column if not exists completed_at timestamptz,
  add column if not exists reviewed boolean not null default false;

-- ============================================================
-- H. Storage bucket for booking photos (private)
-- ============================================================
insert into storage.buckets (id, name, public)
values ('booking-photos', 'booking-photos', false)
on conflict (id) do nothing;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Booking participants can upload booking photos'
  ) then
    create policy "Booking participants can upload booking photos"
      on storage.objects for insert to authenticated
      with check (
        bucket_id = 'booking-photos'
        and exists (
          select 1 from public.booking_photos bp
          where bp.file_path = storage.foldername(name) || '/' || storage.filename(name)
            and bp.uploader_user_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Booking participants can view booking photos'
  ) then
    create policy "Booking participants can view booking photos"
      on storage.objects for select to authenticated
      using (
        bucket_id = 'booking-photos'
        and exists (
          select 1 from public.booking_photos bp
          where bp.file_path = storage.foldername(name) || '/' || storage.filename(name)
            and exists (
              select 1 from public.bookings b
              where b.id = bp.booking_id
                and (b.customer_user_id = auth.uid() or b.provider_user_id = auth.uid())
            )
        )
      );
  end if;
end
$$;

-- ============================================================
-- I. Grants
-- ============================================================
grant select, insert, update on public.reviews to authenticated;
grant select, insert, delete on public.favorites to authenticated;
grant select, insert, update, delete on public.provider_availability to authenticated;
grant select, insert, update on public.service_packages to authenticated;
grant select, insert, update on public.quotes to authenticated;
grant select, insert, update, delete on public.booking_photos to authenticated;
