-- NaijaFix final feature foundation
-- Run in Supabase SQL Editor. This migration does not delete data or replace existing policies.

-- A. Existing profile/provider photo fields
alter table public.profiles
  add column if not exists avatar_url text;

alter table public.providers
  add column if not exists avatar_url text;

-- B. Provider work samples
create table if not exists public.provider_work_samples (
  id bigint generated by default as identity primary key,
  provider_user_id uuid not null,
  image_url text not null,
  caption text,
  created_at timestamptz not null default now()
);

alter table public.provider_work_samples enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'provider_work_samples'
      and policyname = 'Authenticated users can view provider work samples'
  ) then
    create policy "Authenticated users can view provider work samples"
      on public.provider_work_samples
      for select to authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'provider_work_samples'
      and policyname = 'Providers can insert their own work samples'
  ) then
    create policy "Providers can insert their own work samples"
      on public.provider_work_samples
      for insert to authenticated
      with check (provider_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'provider_work_samples'
      and policyname = 'Providers can update their own work samples'
  ) then
    create policy "Providers can update their own work samples"
      on public.provider_work_samples
      for update to authenticated
      using (provider_user_id = auth.uid())
      with check (provider_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'provider_work_samples'
      and policyname = 'Providers can delete their own work samples'
  ) then
    create policy "Providers can delete their own work samples"
      on public.provider_work_samples
      for delete to authenticated
      using (provider_user_id = auth.uid());
  end if;
end
$$;

-- C. Private provider verification records and documents
create table if not exists public.provider_verifications (
  id bigint generated by default as identity primary key,
  provider_user_id uuid not null,
  id_document_url text,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid,
  rejection_reason text
);

alter table public.provider_verifications enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'provider_verifications'
      and policyname = 'Providers can view their own verification'
  ) then
    create policy "Providers can view their own verification"
      on public.provider_verifications
      for select to authenticated
      using (provider_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'provider_verifications'
      and policyname = 'Providers can submit their own verification'
  ) then
    create policy "Providers can submit their own verification"
      on public.provider_verifications
      for insert to authenticated
      with check (provider_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'provider_verifications'
      and policyname = 'Admins can review provider verification'
  ) then
    create policy "Admins can review provider verification"
      on public.provider_verifications
      for all to authenticated
      using (exists (
        select 1 from public.profiles p
        where p.user_id = auth.uid() and p.role = 'admin'
      ))
      with check (exists (
        select 1 from public.profiles p
        where p.user_id = auth.uid() and p.role = 'admin'
      ));
  end if;
end
$$;

-- D. Complaints and reports
create table if not exists public.support_reports (
  id bigint generated by default as identity primary key,
  reporter_user_id uuid not null,
  reporter_role text,
  reported_user_id uuid,
  booking_id bigint,
  category text not null,
  subject text not null,
  description text not null,
  status text not null default 'open'
    check (status in ('open', 'in_review', 'resolved', 'closed')),
  admin_response text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

alter table public.support_reports enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'support_reports'
      and policyname = 'Users can submit reports as themselves'
  ) then
    create policy "Users can submit reports as themselves"
      on public.support_reports
      for insert to authenticated
      with check (reporter_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'support_reports'
      and policyname = 'Users can view their own reports'
  ) then
    create policy "Users can view their own reports"
      on public.support_reports
      for select to authenticated
      using (reporter_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'support_reports'
      and policyname = 'Admins can manage support reports'
  ) then
    create policy "Admins can manage support reports"
      on public.support_reports
      for all to authenticated
      using (exists (
        select 1 from public.profiles p
        where p.user_id = auth.uid() and p.role = 'admin'
      ))
      with check (exists (
        select 1 from public.profiles p
        where p.user_id = auth.uid() and p.role = 'admin'
      ));
  end if;
end
$$;

-- E. Storage buckets. Profile/work-sample images are private by default;
-- clients should use signed URLs. Verification documents are always private.
insert into storage.buckets (id, name, public)
values
  ('profile-photos', 'profile-photos', false),
  ('provider-work-samples', 'provider-work-samples', false),
  ('provider-verification-documents', 'provider-verification-documents', false)
on conflict (id) do nothing;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Users can upload their own profile photos'
  ) then
    create policy "Users can upload their own profile photos"
      on storage.objects for insert to authenticated
      with check (
        bucket_id = 'profile-photos'
        and (storage.foldername(name))[1] = auth.uid()::text
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Users can manage their own profile photos'
  ) then
    create policy "Users can manage their own profile photos"
      on storage.objects for all to authenticated
      using (
        bucket_id = 'profile-photos'
        and (storage.foldername(name))[1] = auth.uid()::text
      )
      with check (
        bucket_id = 'profile-photos'
        and (storage.foldername(name))[1] = auth.uid()::text
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Providers can manage their own work sample files'
  ) then
    create policy "Providers can manage their own work sample files"
      on storage.objects for all to authenticated
      using (
        bucket_id = 'provider-work-samples'
        and (storage.foldername(name))[1] = auth.uid()::text
      )
      with check (
        bucket_id = 'provider-work-samples'
        and (storage.foldername(name))[1] = auth.uid()::text
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Providers can manage their own verification files'
  ) then
    create policy "Providers can manage their own verification files"
      on storage.objects for all to authenticated
      using (
        bucket_id = 'provider-verification-documents'
        and (storage.foldername(name))[1] = auth.uid()::text
      )
      with check (
        bucket_id = 'provider-verification-documents'
        and (storage.foldername(name))[1] = auth.uid()::text
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Admins can review verification files'
  ) then
    create policy "Admins can review verification files"
      on storage.objects for select to authenticated
      using (
        bucket_id = 'provider-verification-documents'
        and exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;
end
$$;

-- Required grants for the client roles. RLS remains authoritative.
grant select on public.provider_work_samples to authenticated;
grant insert, update, delete on public.provider_work_samples to authenticated;
grant select, insert on public.provider_verifications to authenticated;
grant select, insert on public.support_reports to authenticated;
grant select, update on public.support_reports to authenticated;
