const serviceImageSlugs = new Set([
  'accounting',
  'ac-repair',
  'aluminium-glass',
  'auto-electrical',
  'auto-mechanic',
  'bag-making',
  'barbering',
  'beauty',
  'borehole-services',
  'braiding-locs',
  'cake-baking',
  'car-ac-repair',
  'car-battery-services',
  'car-detailing',
  'car-painting',
  'car-wash',
  'carpentry',
  'catering',
  'cctv-installation',
  'cleaning',
  'clothing-alteration',
  'computer-repair',
  'digital-marketing',
  'dispatch-riders',
  'dj',
  'document-delivery',
  'driver-chauffeur',
  'driving-instructor',
  'dry-cleaning',
  'dstv-satellite',
  'elderly-care',
  'electrical',
  'electronics-repair',
  'equipment-rentals',
  'errand-runner',
  'event-decoration',
  'event-photography',
  'event-planning',
  'event-videography',
  'fashion-tailoring',
  'fitness-trainer',
  'food-delivery',
  'fumigation-pest-control',
  'furniture-making',
  'furniture-repair',
  'gardening-landscaping',
  'generator-repair',
  'graphic-design',
  'grocery-delivery',
  'hairdressing',
  'handyman',
  'home-cook',
  'home-tutor',
  'house-building',
  'interior-decoration',
  'inverter-installation',
  'inverter-repair',
  'jamb-waec-tutor',
  'language-tutor',
  'laptop-repair',
  'laundry',
  'legal-services',
  'makeup-artist',
  'manicure-pedicure',
  'massage',
  'mc-compere',
  'mobile-app-development',
  'moving-relocation',
  'music-teacher',
  'nail-technician',
  'nanny-childcare',
  'network-installation',
  'package-delivery',
  'painting',
  'panel-beating',
  'pet-grooming',
  'pet-sitting',
  'pet-walking',
  'phone-repair',
  'photography',
  'pickup-dropoff',
  'plastering-screeding',
  'plumbing',
  'pop-ceiling',
  'primary-secondary-tutor',
  'printer-repair',
  'printing-services',
  'professional-consulting',
  'recruitment-services',
  'roofing',
  'security-systems',
  'shoe-making',
  'shoe-repair',
  'small-chops',
  'social-media-management',
  'solar-installation',
  'solar-repair',
  'sound-lighting',
  'tax-services',
  'tiling-flooring',
  'towing',
  'translation',
  'travel-tour-services',
  'tv-repair',
  'tyre-services',
  'video-editing',
  'videography',
  'virtual-assistant',
  'vulcanizing',
  'water-pump-repair',
  'water-tank-services',
  'web-development',
  'welding-fabrication',
  'wifi-internet-setup',
])

export function getServiceImage(service) {
  if (!service) return null
  const slug = String(service.slug || service.id || '').toLowerCase().trim()
  if (!slug || !serviceImageSlugs.has(slug)) return null
  return `/images/services/${slug}.png`
}

export function getServiceImageByKey(key) {
  if (!key) return null
  const slug = String(key).toLowerCase().trim()
  if (!slug || !serviceImageSlugs.has(slug)) return null
  return `/images/services/${slug}.png`
}

export function getServiceIcon(service) {
  const category = normalizeCategory(service?.category)
  const name = normalizeCategory(service?.name)
  return serviceIcons[category] || serviceIcons[name] || '붿뿯붿붿'
}

export function getServiceGradient(service) {
  if (!service) return 'linear-gradient(135deg, #087f3d, #066630)'
  const category = normalizeCategory(service.category)
  const gradients = {
    'home-construction': 'linear-gradient(135deg, #8B5E3C, #5D4037)',
    'power-security': 'linear-gradient(135deg, #F59E0B, #D97706)',
    'auto-transport': 'linear-gradient(135deg, #3B82F6, #1E40AF)',
    'delivery-errands': 'linear-gradient(135deg, #10B981, #059669)',
    'technology-digital': 'linear-gradient(135deg, #6366F1, #4F46E5)',
    'beauty-personal-care': 'linear-gradient(135deg, #EC4899, #BE185D)',
    'family-education': 'linear-gradient(135deg, #8B5CF6, #6D28D9)',
    'fashion-laundry': 'linear-gradient(135deg, #F97316, #C2410C)',
    'events-food': 'linear-gradient(135deg, #EF4444, #B91C1C)',
    'professional-services': 'linear-gradient(135deg, #0EA5E9, #0369A1)',
  }
  return gradients[category] || 'linear-gradient(135deg, #087f3d, #066630)'
}

function normalizeCategory(value) {
  return String(value || '')
    .trim()
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[-_]/g, ' ')
    .replace(/\s+/g, ' ')
}

const serviceIcons = {
  plumbing: '붿붿',
  electrical: '뿯⚽',
  cleaning: '붿뿯붿',
  'ac repair': '❄붿',
  'generator repair': '붿붿',
  'phone repair': '붿뿯붿',
  'computer repair': '�붿',
  carpentry: '�붿',
  painting: '�붿',
  'fashion and tailoring': '붿붿',
  barbering: '�붿',
  beauty: '�붿',
  'house building and construction': '붿뿯붿붿',
  roofing: '붿뿯붿',
  'tiling and flooring': '붿붿',
  'pop and ceiling': '✨',
  'plastering and screeding': '붿뿯붿',
  'welding and fabrication': '뿯⚽붿',
  'aluminium and glass': '�붿',
  'furniture making': '�붿',
  'furniture repair': '붿붿',
  'interior decoration': '�붿',
  handyman: '붿붿',
  'gardening and landscaping': '붿붿',
  'fumigation and pest control': '붿붿',
  'solar installation': '☀붿',
  'solar repair': '붿붿',
  'inverter installation': '붿붿',
  'cctv installation': '붿뿯붿',
  'dstv / satellite installation': '붿뿯붿',
  'borehole services': '�붿',
  'water pump repair': '붿붿',
  'auto mechanic': '�붿',
  'auto electrical': '뿯⚽',
  'car detailing': '✨',
  'car painting': '�붿',
  'panel beating': '붿붿',
  'car battery services': '붿붿',
  'driver / chauffeur': '붿뿯붿‍✈붿',
  'moving and relocation': '붿뿯붿',
  'dispatch riders': '붿뿯붿붿',
  'food delivery': '붿붿',
  'grocery delivery': '붿뿯붿',
  'document delivery': '붿뿯붿',
  'pickup and drop-off': '붿뿯붿',
  'laptop repair': '�붿',
  'printer repair': '�붿붿',
  'tv repair': '붿뿯붿',
  'wi-fi and internet setup': '붿뿯붿',
  'network installation': '붿붿',
  'web development': '�붿',
  'mobile app development': '붿뿯붿',
  'graphic design': '�붿',
  'video editing': '�붿',
  photography: '붿뿯붿',
  videography: '�붿',
  'digital marketing': '붿뿯붿',
  'virtual assistant': '붿뿯붿‍�붿',
  hairdressing: '�붿',
  'braiding / locs': '�붿‍♀붿',
  'makeup artist': '�붿',
  'nail technician': '�붿',
  'manicure and pedicure': '�붿',
  massage: '�붿',
  'fitness trainer': '붿뿯붿붿',
  'home tutor': '붿뿯붿',
  'jamb / waec tutor': '붿뿯붿',
  'primary / secondary tutor': '붿뿯붿',
  'music teacher': '�붿',
  'language tutor': '붿뿯붿붿',
  'driving instructor': '�붿',
  'nanny / childcare': '붿붿',
  'elderly care / caregiver': '붿뿯붿',
  'home cook / personal chef': '붿붿‍붿붿',
  'shoe making': '붿붿',
  'bag making': '붿붿',
  laundry: '붿붿',
  'dry cleaning': '붿뿯붿',
  catering: '붿붿붿',
  'small chops': '붿붿',
  'cake and baking': '�붿',
  'event planning': '붿뿯붿',
  'event decoration': '�붿',
  dj: '�붿',
  'mc / compere': '�붿',
  'sound and lighting': '붿붿',
  'event photography': '붿뿯붿',
  'event videography': '�붿',
  'equipment rentals': '�붿',
  'pet grooming': '붿붿',
  'pet sitting': '붿붿',
  'pet walking': '붿붿‍�붿',
  accounting: '붿뿯붿',
  'tax services': '�붿',
  'recruitment services': '붿붿',
  'travel / tour services': '✈붿',
  'printing services': '�붿붿',
  translation: '붿붿',
  'professional consulting': '�붿',
}

const flatServiceImages = {}
export const localServiceImages = {}

export default serviceImageSlugs
