const serviceImageSlugs = new Set([
  'accounting',
  'ac-repair',
  'aluminium-glass',
  'auto-electrical',
  'auto-mechanic',
  'bag-making',
  'barbering',
  'beauty',
  'borehole-services',
  'braiding-locs',
  'cake-baking',
  'car-ac-repair',
  'car-battery-services',
  'car-detailing',
  'car-painting',
  'car-wash',
  'carpentry',
  'catering',
  'cctv-installation',
  'cleaning',
  'clothing-alteration',
  'computer-repair',
  'digital-marketing',
  'dispatch-riders',
  'dj',
  'document-delivery',
  'driver-chauffeur',
  'driving-instructor',
  'dry-cleaning',
  'dstv-satellite',
  'elderly-care',
  'electrical',
  'electronics-repair',
  'equipment-rentals',
  'errand-runner',
  'event-decoration',
  'event-photography',
  'event-planning',
  'event-videography',
  'fashion-tailoring',
  'fitness-trainer',
  'food-delivery',
  'fumigation-pest-control',
  'furniture-making',
  'furniture-repair',
  'gardening-landscaping',
  'generator-repair',
  'graphic-design',
  'grocery-delivery',
  'hairdressing',
  'handyman',
  'home-cook',
  'home-tutor',
  'house-building',
  'interior-decoration',
  'inverter-installation',
  'inverter-repair',
  'jamb-waec-tutor',
  'language-tutor',
  'laptop-repair',
  'laundry',
  'legal-services',
  'makeup-artist',
  'manicure-pedicure',
  'massage',
  'mc-compere',
  'mobile-app-development',
  'moving-relocation',
  'music-teacher',
  'nail-technician',
  'nanny-childcare',
  'network-installation',
  'package-delivery',
  'painting',
  'panel-beating',
  'pet-grooming',
  'pet-sitting',
  'pet-walking',
  'phone-repair',
  'photography',
  'pickup-dropoff',
  'plastering-screeding',
  'plumbing',
  'pop-ceiling',
  'primary-secondary-tutor',
  'printer-repair',
  'printing-services',
  'professional-consulting',
  'recruitment-services',
  'roofing',
  'security-systems',
  'shoe-making',
  'shoe-repair',
  'small-chops',
  'social-media-management',
  'solar-installation',
  'solar-repair',
  'sound-lighting',
  'tax-services',
  'tiling-flooring',
  'towing',
  'translation',
  'travel-tour-services',
  'tv-repair',
  'tyre-services',
  'video-editing',
  'videography',
  'virtual-assistant',
  'vulcanizing',
  'water-pump-repair',
  'water-tank-services',
  'web-development',
  'welding-fabrication',
  'wifi-internet-setup',
])

export function getServiceImage(service) {
  if (!service) return null
  const slug = String(service.slug || service.id || '').toLowerCase().trim()
  if (!slug || !serviceImageSlugs.has(slug)) return null
  return `/images/services/${slug}.png`
}

export function getServiceImageByKey(key) {
  if (!key) return null
  const slug = String(key).toLowerCase().trim()
  if (!slug || !serviceImageSlugs.has(slug)) return null
  return `/images/services/${slug}.png`
}

export function getServiceIcon(service) {
  const category = normalizeCategory(service?.category)
  const name = normalizeCategory(service?.name)
  return serviceIcons[category] || serviceIcons[name] || '🛠️'
}

export function getServiceGradient(service) {
  if (!service) return 'linear-gradient(135deg, #087f3d, #066630)'
  const category = normalizeCategory(service.category)
  const gradients = {
    'home-construction': 'linear-gradient(135deg, #8B5E3C, #5D4037)',
    'power-security': 'linear-gradient(135deg, #F59E0B, #D97706)',
    'auto-transport': 'linear-gradient(135deg, #3B82F6, #1E40AF)',
    'delivery-errands': 'linear-gradient(135deg, #10B981, #059669)',
    'technology-digital': 'linear-gradient(135deg, #6366F1, #4F46E5)',
    'beauty-personal-care': 'linear-gradient(135deg, #EC4899, #BE185D)',
    'family-education': 'linear-gradient(135deg, #8B5CF6, #6D28D9)',
    'fashion-laundry': 'linear-gradient(135deg, #F97316, #C2410C)',
    'events-food': 'linear-gradient(135deg, #EF4444, #B91C1C)',
    'professional-services': 'linear-gradient(135deg, #0EA5E9, #0369A1)',
  }
  return gradients[category] || 'linear-gradient(135deg, #087f3d, #066630)'
}

function normalizeCategory(value) {
  return String(value || '')
    .trim()
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[-_]/g, ' ')
    .replace(/\s+/g, ' ')
}

const serviceIcons = {
  plumbing: '🔧',
  electrical: '⚡',
  cleaning: '🧹',
  'ac repair': '❄️',
  'generator repair': '🔌',
  'phone repair': '📱',
  'computer repair': '💻',
  carpentry: '🪚',
  painting: '🎨',
  'fashion and tailoring': '👕',
  barbering: '💈',
  beauty: '💇',
  'house building and construction': '🏗️',
  roofing: '🏠',
  'tiling and flooring': '🔲',
  'pop and ceiling': '✨',
  'plastering and screeding': '🧱',
  'welding and fabrication': '⚒️',
  'aluminium and glass': '🪟',
  'furniture making': '🪑',
  'furniture repair': '🔨',
  'interior decoration': '🎨',
  handyman: '🔧',
  'gardening and landscaping': '🌿',
  'fumigation and pest control': '🐛',
  'solar installation': '☀️',
  'solar repair': '🔆',
  'inverter installation': '🔋',
  'cctv installation': '📹',
  'dstv / satellite installation': '📡',
  'borehole services': '💧',
  'water pump repair': '🔧',
  'auto mechanic': '🚗',
  'auto electrical': '⚡',
  'car detailing': '✨',
  'car painting': '🎨',
  'panel beating': '🔨',
  'car battery services': '🔋',
  'driver / chauffeur': '🧑‍✈️',
  'moving and relocation': '📦',
  'dispatch riders': '🏍️',
  'food delivery': '🍱',
  'grocery delivery': '🛒',
  'document delivery': '📄',
  'pickup and drop-off': '📍',
  'laptop repair': '💻',
  'printer repair': '🖨️',
  'tv repair': '📺',
  'wi-fi and internet setup': '📶',
  'network installation': '🌐',
  'web development': '💻',
  'mobile app development': '📱',
  'graphic design': '🎨',
  'video editing': '🎬',
  photography: '📷',
  videography: '🎥',
  'digital marketing': '📈',
  'virtual assistant': '🧑‍💻',
  hairdressing: '💇',
  'braiding / locs': '💇‍♀️',
  'makeup artist': '💄',
  'nail technician': '💅',
  'manicure and pedicure': '💅',
  massage: '💆',
  'fitness trainer': '🏋️',
  'home tutor': '📚',
  'jamb / waec tutor': '📝',
  'primary / secondary tutor': '📖',
  'music teacher': '🎵',
  'language tutor': '🗣️',
  'driving instructor': '🚗',
  'nanny / childcare': '👶',
  'elderly care / caregiver': '🧓',
  'home cook / personal chef': '👨‍🍳',
  'shoe making': '👞',
  'bag making': '👜',
  laundry: '👕',
  'dry cleaning': '🧥',
  catering: '🍽️',
  'small chops': '🥟',
  'cake and baking': '🎂',
  'event planning': '📋',
  'event decoration': '🎊',
  dj: '🎧',
  'mc / compere': '🎤',
  'sound and lighting': '🔊',
  'event photography': '📸',
  'event videography': '🎬',
  'equipment rentals': '🎪',
  'pet grooming': '🐕',
  'pet sitting': '🐾',
  'pet walking': '🐕‍🦺',
  accounting: '📊',
  'tax services': '💰',
  'recruitment services': '🤝',
  'travel / tour services': '✈️',
  'printing services': '🖨️',
  translation: '🌍',
  'professional consulting': '💼',
}

const flatServiceImages = {}
export const localServiceImages = {}

export default serviceImageSlugs
