-- NaijaFix: Global media architecture extension
-- Idempotent: safe to run multiple times.
-- Preserves existing data and policies.

-- ============================================================
-- A. Service images
-- ============================================================
alter table public.services
  add column if not exists image_url text;

-- ============================================================
-- B. Provider profile media
-- ============================================================
alter table public.providers
  add column if not exists cover_image_url text,
  add column if not exists logo_url text;

-- ============================================================
-- C. Advertisements table (Supabase-backed)
-- ============================================================
create table if not exists public.advertisements (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image_url text,
  video_url text,
  cta_text text,
  label text not null default 'Sponsored',
  position text not null default 'inline',
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.advertisements enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'advertisements'
      and policyname = 'Anyone can view active ads'
  ) then
    create policy "Anyone can view active ads"
      on public.advertisements
      for select to authenticated
      using (active = true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'advertisements'
      and policyname = 'Admins can manage ads'
  ) then
    create policy "Admins can manage ads"
      on public.advertisements
      for all to authenticated
      using (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      )
      with check (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;
end
$$;

create index if not exists idx_advertisements_active
  on public.advertisements (active, sort_order);

grant select on public.advertisements to authenticated;
grant insert, update, delete on public.advertisements to authenticated;

-- ============================================================
-- D. Storage buckets
-- ============================================================
insert into storage.buckets (id, name, public)
values
  ('service-images', 'service-images', true),
  ('provider-media', 'provider-media', false),
  ('ad-images', 'ad-images', true)
on conflict (id) do nothing;

-- ============================================================
-- E. Storage RLS policies
-- ============================================================
do $$
begin
  -- Service images: public read, admin write
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Public can view service images'
  ) then
    create policy "Public can view service images"
      on storage.objects for select to public
      using (bucket_id = 'service-images');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Admins can upload service images'
  ) then
    create policy "Admins can upload service images"
      on storage.objects for insert to authenticated
      with check (
        bucket_id = 'service-images'
        and exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Admins can manage service images'
  ) then
    create policy "Admins can manage service images"
      on storage.objects for all to authenticated
      using (
        bucket_id = 'service-images'
        and exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      )
      with check (
        bucket_id = 'service-images'
        and exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;

  -- Provider media: provider can manage own, authenticated can view
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Providers can upload their own media'
  ) then
    create policy "Providers can upload their own media"
      on storage.objects for insert to authenticated
      with check (
        bucket_id = 'provider-media'
        and (storage.foldername(name))[1] = auth.uid()::text
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Providers can manage their own media'
  ) then
    create policy "Providers can manage their own media"
      on storage.objects for all to authenticated
      using (
        bucket_id = 'provider-media'
        and (storage.foldername(name))[1] = auth.uid()::text
      )
      with check (
        bucket_id = 'provider-media'
        and (storage.foldername(name))[1] = auth.uid()::text
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Authenticated users can view provider media'
  ) then
    create policy "Authenticated users can view provider media"
      on storage.objects for select to authenticated
      using (bucket_id = 'provider-media');
  end if;

  -- Ad images: public read, admin write
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Public can view ad images'
  ) then
    create policy "Public can view ad images"
      on storage.objects for select to public
      using (bucket_id = 'ad-images');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Admins can upload ad images'
  ) then
    create policy "Admins can upload ad images"
      on storage.objects for insert to authenticated
      with check (
        bucket_id = 'ad-images'
        and exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Admins can manage ad images'
  ) then
    create policy "Admins can manage ad images"
      on storage.objects for all to authenticated
      using (
        bucket_id = 'ad-images'
        and exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      )
      with check (
        bucket_id = 'ad-images'
        and exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;
end
$$;
