-- NaijaFix: Extend services table and create provider_services
-- Idempotent: safe to run multiple times.
-- Preserves existing data.

-- ============================================================
-- A. Extend public.services table
-- ============================================================
alter table public.services
  add column if not exists slug text,
  add column if not exists active boolean not null default true,
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS icon text,
  ADD COLUMN IF NOT EXISTS sort_order integer not null default 0,
  ADD COLUMN IF NOT EXISTS created_at timestamptz not null default now();

-- Create unique index on slug if it doesn't exist
create unique index if not exists services_slug_key
  on public.services (slug)
  where slug is not null;

-- Create index on category for filtering
create index if not exists idx_services_category
  on public.services (category);

-- Create index on active status for filtering
create index if not exists idx_services_active
  on public.services (active);

-- Enable RLS on services if not already enabled
alter table public.services enable row level security;

-- RLS policies for services (public read, admin manage)
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'services'
      and policyname = 'Anyone can view active services'
  ) then
    create policy "Anyone can view active services"
      on public.services
      for select to authenticated
      using (active = true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'services'
      and policyname = 'Admins can manage services'
  ) then
    create policy "Admins can manage services"
      on public.services
      for all to authenticated
      using (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      )
      with check (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;
end
$$;

grant select on public.services to authenticated;
grant insert, update, delete on public.services to authenticated;

-- ============================================================
-- B. Create provider_services relationship table
-- ============================================================
create table if not exists public.provider_services (
  id bigint generated by default as identity primary key,
  provider_user_id uuid not null,
  service_id bigint not null,
  created_at timestamptz not null default now(),
  unique (provider_user_id, service_id)
);

alter table public.provider_services enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'provider_services'
      and policyname = 'Providers can view their own service relationships'
  ) then
    create policy "Providers can view their own service relationships"
      on public.provider_services
      for select to authenticated
      using (provider_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'provider_services'
      and policyname = 'Anyone can view provider-service relationships'
  ) then
    create policy "Anyone can view provider-service relationships"
      on public.provider_services
      for select to authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'provider_services'
      and policyname = 'Providers can manage their own service relationships'
  ) then
    create policy "Providers can manage their own service relationships"
      on public.provider_services
      for all to authenticated
      using (provider_user_id = auth.uid())
      with check (provider_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'provider_services'
      and policyname = 'Admins can manage provider services'
  ) then
    create policy "Admins can manage provider services"
      on public.provider_services
      for all to authenticated
      using (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      )
      with check (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;
end
$$;

create index if not exists idx_provider_services_provider
  on public.provider_services (provider_user_id);

create index if not exists idx_provider_services_service
  on public.provider_services (service_id);

grant select, insert, update, delete on public.provider_services to authenticated;
