-- NaijaFix: Restaurants, menu categories, and menu items
-- Idempotent: safe to run multiple times.
-- Preserves existing data.

-- ============================================================
-- A. Restaurants table
-- ============================================================
create table if not exists public.restaurants (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null,
  name text not null,
  description text,
  phone text,
  email text,
  address text,
  city text,
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  logo_url text,
  cover_image_url text,
  cuisine text,
  delivery_fee numeric(10, 2) not null default 0,
  estimated_delivery_minutes integer not null default 30,
  rating numeric(3, 2) not null default 0,
  is_open boolean not null default true,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.restaurants enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'restaurants'
      and policyname = 'Anyone can view active restaurants'
  ) then
    create policy "Anyone can view active restaurants"
      on public.restaurants
      for select to authenticated
      using (is_active = true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'restaurants'
      and policyname = 'Restaurant owners can manage their own restaurant'
  ) then
    create policy "Restaurant owners can manage their own restaurant"
      on public.restaurants
      for all to authenticated
      using (owner_user_id = auth.uid())
      with check (owner_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'restaurants'
      and policyname = 'Admins can manage all restaurants'
  ) then
    create policy "Admins can manage all restaurants"
      on public.restaurants
      for all to authenticated
      using (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      )
      with check (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;
end
$$;

create index if not exists idx_restaurants_owner
  on public.restaurants (owner_user_id);

create index if not exists idx_restaurants_city
  on public.restaurants (city);

create index if not exists idx_restaurants_cuisine
  on public.restaurants (cuisine);

create index if not exists idx_restaurants_active
  on public.restaurants (is_active, is_open);

grant select, insert, update, delete on public.restaurants to authenticated;

-- ============================================================
-- B. Restaurant menu categories
-- ============================================================
create table if not exists public.restaurant_menu_categories (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  name text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.restaurant_menu_categories enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'restaurant_menu_categories'
      and policyname = 'Anyone can view menu categories'
  ) then
    create policy "Anyone can view menu categories"
      on public.restaurant_menu_categories
      for select to authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'restaurant_menu_categories'
      and policyname = 'Restaurant owners can manage their menu categories'
  ) then
    create policy "Restaurant owners can manage their menu categories"
      on public.restaurant_menu_categories
      for all to authenticated
      using (
        exists (
          select 1 from public.restaurants r
          where r.id = restaurant_id and r.owner_user_id = auth.uid()
        )
      )
      with check (
        exists (
          select 1 from public.restaurants r
          where r.id = restaurant_id and r.owner_user_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'restaurant_menu_categories'
      and policyname = 'Admins can manage menu categories'
  ) then
    create policy "Admins can manage menu categories"
      on public.restaurant_menu_categories
      for all to authenticated
      using (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      )
      with check (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;
end
$$;

create index if not exists idx_menu_categories_restaurant
  on public.restaurant_menu_categories (restaurant_id, sort_order);

grant select, insert, update, delete on public.restaurant_menu_categories to authenticated;

-- ============================================================
-- C. Restaurant menu items
-- ============================================================
create table if not exists public.restaurant_menu_items (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  category_id bigint references public.restaurant_menu_categories(id) on delete set null,
  name text not null,
  description text,
  price numeric(10, 2) not null,
  image_url text,
  available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.restaurant_menu_items enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'restaurant_menu_items'
      and policyname = 'Anyone can view available menu items'
  ) then
    create policy "Anyone can view available menu items"
      on public.restaurant_menu_items
      for select to authenticated
      using (available = true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'restaurant_menu_items'
      and policyname = 'Restaurant owners can manage their menu items'
  ) then
    create policy "Restaurant owners can manage their menu items"
      on public.restaurant_menu_items
      for all to authenticated
      using (
        exists (
          select 1 from public.restaurants r
          where r.id = restaurant_id and r.owner_user_id = auth.uid()
        )
      )
      with check (
        exists (
          select 1 from public.restaurants r
          where r.id = restaurant_id and r.owner_user_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'restaurant_menu_items'
      and policyname = 'Admins can manage menu items'
  ) then
    create policy "Admins can manage menu items"
      on public.restaurant_menu_items
      for all to authenticated
      using (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      )
      with check (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;
end
$$;

create index if not exists idx_menu_items_restaurant
  on public.restaurant_menu_items (restaurant_id);

create index if not exists idx_menu_items_category
  on public.restaurant_menu_items (category_id);

create index if not exists idx_menu_items_available
  on public.restaurant_menu_items (available);

grant select, insert, update, delete on public.restaurant_menu_items to authenticated;
