-- NaijaFix Phase 1 marketplace retention and trust foundation.
-- Safe, idempotent migration.
-- Does NOT drop tables, delete data, reset the database, or overwrite existing rows.

-- ============================================================
-- A. Customer rewards foundation
-- ============================================================
create table if not exists public.customer_rewards (
  id bigint generated by default as identity primary key,
  customer_user_id uuid not null references public.profiles(user_id) on delete cascade,
  points_balance integer not null default 0,
  lifetime_points integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (customer_user_id)
);

alter table public.customer_rewards enable row level security;

create table if not exists public.customer_reward_transactions (
  id bigint generated by default as identity primary key,
  customer_user_id uuid not null references public.profiles(user_id) on delete cascade,
  points_delta integer not null,
  balance_after integer not null,
  reason text,
  created_by uuid,
  created_at timestamptz not null default now()
);

alter table public.customer_reward_transactions enable row level security;

-- ============================================================
-- B. Marketplace configuration (commission foundation only)
-- ============================================================
create table if not exists public.marketplace_settings (
  id integer primary key check (id = 1),
  service_commission_percent numeric(5, 2) not null default 0,
  restaurant_commission_percent numeric(5, 2) not null default 0,
  delivery_margin_percent numeric(5, 2) not null default 0,
  updated_at timestamptz not null default now()
);

insert into public.marketplace_settings (id, service_commission_percent, restaurant_commission_percent, delivery_margin_percent)
values (1, 0, 0, 0)
on conflict (id) do nothing;

alter table public.marketplace_settings enable row level security;

-- ============================================================
-- C. Future protected-payment architecture on bookings
-- ============================================================
alter table public.bookings
  add column if not exists payment_status text,
  add column if not exists payment_authorized_at timestamptz,
  add column if not exists payment_completed_at timestamptz,
  add column if not exists payment_failed_at timestamptz,
  add column if not exists refund_pending_at timestamptz,
  add column if not exists refunded_at timestamptz;

-- ============================================================
-- D. RLS policies for customer_rewards
-- ============================================================
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'customer_rewards'
      and policyname = 'Customers can view their own rewards'
  ) then
    create policy "Customers can view their own rewards"
      on public.customer_rewards for select to authenticated
      using (customer_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'customer_rewards'
      and policyname = 'Admins can manage customer rewards'
  ) then
    create policy "Admins can manage customer rewards"
      on public.customer_rewards for all to authenticated
      using (exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.role = 'admin'))
      with check (exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.role = 'admin'));
  end if;
end
$$;

-- ============================================================
-- E. RLS policies for customer_reward_transactions (audit trail)
-- ============================================================
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'customer_reward_transactions'
      and policyname = 'Customers can view their own reward transactions'
  ) then
    create policy "Customers can view their own reward transactions"
      on public.customer_reward_transactions for select to authenticated
      using (customer_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'customer_reward_transactions'
      and policyname = 'Admins can view all reward transactions'
  ) then
    create policy "Admins can view all reward transactions"
      on public.customer_reward_transactions for select to authenticated
      using (exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.role = 'admin'));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'customer_reward_transactions'
      and policyname = 'No direct user inserts into reward transactions'
  ) then
    create policy "No direct user inserts into reward transactions"
      on public.customer_reward_transactions for insert to authenticated
      with check (false);
  end if;
end
$$;

-- ============================================================
-- F. RLS policies for marketplace_settings
-- ============================================================
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'marketplace_settings'
      and policyname = 'Authenticated users can view marketplace settings'
  ) then
    create policy "Authenticated users can view marketplace settings"
      on public.marketplace_settings for select to authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'marketplace_settings'
      and policyname = 'Admins can manage marketplace settings'
  ) then
    create policy "Admins can manage marketplace settings"
      on public.marketplace_settings for all to authenticated
      using (exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.role = 'admin'))
      with check (exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.role = 'admin'));
  end if;
end
$$;

-- ============================================================
-- G. Grants for new tables (RLS remains authoritative)
-- ============================================================
grant select on public.customer_rewards to authenticated;
grant select on public.customer_reward_transactions to authenticated;
grant select on public.marketplace_settings to authenticated;
grant insert, update on public.customer_rewards to authenticated;

-- ============================================================
-- H. Indexes
-- ============================================================
create index if not exists idx_customer_rewards_customer
  on public.customer_rewards (customer_user_id);

create index if not exists idx_customer_reward_transactions_customer
  on public.customer_reward_transactions (customer_user_id, created_at desc);

create index if not exists idx_bookings_payment_status
  on public.bookings (payment_status);

-- ============================================================
-- I. Hardened SECURITY DEFINER RPC functions
-- All functions:
--   * SET search_path = '' to prevent search-path injection
--   * schema-qualify every table reference
--   * run with SECURITY DEFINER so RLS is bypassed in a controlled way
--   * are narrowly granted to authenticated only (not public/anon)
-- ============================================================

-- I.1 Provider reputation (read-only, calculated from REAL data only)
create or replace function public.get_provider_reputation(p_provider_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_total bigint;
  v_completed bigint;
  v_cancelled bigint;
  v_declined bigint;
  v_avg_rating numeric;
  v_review_count bigint;
  v_favorites_count bigint;
begin
  select count(*) into v_total
    from public.bookings b
   where b.provider_user_id = p_provider_user_id;

  select count(*) into v_completed
    from public.bookings b
   where b.provider_user_id = p_provider_user_id
     and lower(coalesce(b.status, '')) = 'completed';

  select count(*) into v_cancelled
    from public.bookings b
   where b.provider_user_id = p_provider_user_id
     and lower(coalesce(b.status, '')) = 'cancelled';

  select count(*) into v_declined
    from public.bookings b
   where b.provider_user_id = p_provider_user_id
     and lower(coalesce(b.status, '')) = 'declined';

  select coalesce(avg(r.rating), 0) into v_avg_rating
    from public.reviews r
   where r.provider_user_id = p_provider_user_id;

  select count(*) into v_review_count
    from public.reviews r
   where r.provider_user_id = p_provider_user_id;

  select count(*) into v_favorites_count
    from public.favorites f
   where f.provider_user_id = p_provider_user_id;

  return jsonb_build_object(
    'provider_user_id', p_provider_user_id,
    'total_bookings', coalesce(v_total, 0),
    'completed_bookings', coalesce(v_completed, 0),
    'cancelled_bookings', coalesce(v_cancelled, 0),
    'declined_bookings', coalesce(v_declined, 0),
    'review_count', coalesce(v_review_count, 0),
    'average_rating', round(coalesce(v_avg_rating, 0)::numeric, 1),
    'favorite_count', coalesce(v_favorites_count, 0)
  );
end;
$$;

-- I.2 Customer rewards (read-only lookup)
create or replace function public.get_customer_rewards(p_customer_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row public.customer_rewards%rowtype;
begin
  select * into v_row
    from public.customer_rewards cr
   where cr.customer_user_id = p_customer_user_id;

  if not found then
    return jsonb_build_object(
      'customer_user_id', p_customer_user_id,
      'points_balance', 0,
      'lifetime_points', 0
    );
  end if;

  return jsonb_build_object(
    'customer_user_id', v_row.customer_user_id,
    'points_balance', coalesce(v_row.points_balance, 0),
    'lifetime_points', coalesce(v_row.lifetime_points, 0)
  );
end;
$$;

-- I.3 Adjust customer points (mutation, restricted to server-side callers only)
-- SECURITY: This function is NOT granted to authenticated users.
-- Only the service_role (and future server-side triggers) may execute it.
create or replace function public.adjust_customer_points(
  p_customer_user_id uuid,
  p_points_delta integer,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row public.customer_rewards%rowtype;
  v_new_balance integer;
  v_new_lifetime integer;
begin
  if p_points_delta is null then
    raise exception 'points_delta is required';
  end if;

  insert into public.customer_rewards (customer_user_id, points_balance, lifetime_points, updated_at)
  values (p_customer_user_id, 0, 0, now())
  on conflict (customer_user_id) do nothing;

  select * into v_row
    from public.customer_rewards cr
   where cr.customer_user_id = p_customer_user_id
   for update;

  v_new_balance := coalesce(v_row.points_balance, 0) + p_points_delta;
  v_new_lifetime := coalesce(v_row.lifetime_points, 0) + p_points_delta;

  update public.customer_rewards cr
     set points_balance = case when v_new_lifetime >= 0 then greatest(v_new_balance, 0) else v_new_balance end,
         lifetime_points = v_new_lifetime,
         updated_at = now()
   where cr.customer_user_id = p_customer_user_id;

  select * into v_row
    from public.customer_rewards cr
   where cr.customer_user_id = p_customer_user_id;

  insert into public.customer_reward_transactions (
    customer_user_id,
    points_delta,
    balance_after,
    reason,
    created_by,
    created_at
  ) values (
    p_customer_user_id,
    p_points_delta,
    coalesce(v_row.points_balance, 0),
    p_reason,
    null,
    now()
  );

  return jsonb_build_object(
    'customer_user_id', p_customer_user_id,
    'points_balance', coalesce(v_row.points_balance, 0),
    'lifetime_points', coalesce(v_row.lifetime_points, 0)
  );
end;
$$;

-- ============================================================
-- J. Function execution grants and revokes
-- ============================================================
-- These functions are SECURITY DEFINER. By default Postgres grants
-- EXECUTE to PUBLIC. We explicitly revoke from public/anon and grant
-- only to the roles that genuinely need them.

revoke execute on function public.get_provider_reputation(uuid) from public;
revoke execute on function public.get_provider_reputation(uuid) from anon;
grant execute on function public.get_provider_reputation(uuid) to authenticated;

revoke execute on function public.get_customer_rewards(uuid) from public;
revoke execute on function public.get_customer_rewards(uuid) from anon;
grant execute on function public.get_customer_rewards(uuid) to authenticated;

-- adjust_customer_points is intentionally NOT granted to authenticated.
-- Only service_role may execute it (service_role bypasses GRANT checks).
revoke execute on function public.adjust_customer_points(uuid, integer, text) from public;
revoke execute on function public.adjust_customer_points(uuid, integer, text) from anon;
revoke execute on function public.adjust_customer_points(uuid, integer, text) from authenticated;
grant execute on function public.adjust_customer_points(uuid, integer, text) to service_role;