-- NaijaFix: Provider portfolio/work samples
-- Idempotent: safe to run multiple times.
-- Preserves existing data and policies.

-- ============================================================
-- A. Create provider_portfolio_items table
-- ============================================================
create table if not exists public.provider_portfolio_items (
  id bigint generated by default as identity primary key,
  provider_user_id uuid not null,
  service_id bigint null,
  title text not null,
  description text,
  image_url text not null,
  before_image_url text,
  after_image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_provider_portfolio_items_provider
  on public.provider_portfolio_items (provider_user_id);

create index if not exists idx_provider_portfolio_items_service
  on public.provider_portfolio_items (service_id);

create index if not exists idx_provider_portfolio_items_created_at
  on public.provider_portfolio_items (created_at);

-- ============================================================
-- B. RLS on provider_portfolio_items
-- ============================================================
alter table public.provider_portfolio_items enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'provider_portfolio_items'
      and policyname = 'Providers can view their own portfolio items'
  ) then
    create policy "Providers can view their own portfolio items"
      on public.provider_portfolio_items
      for select to authenticated
      using (provider_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'provider_portfolio_items'
      and policyname = 'Authenticated users can view portfolio items'
  ) then
    create policy "Authenticated users can view portfolio items"
      on public.provider_portfolio_items
      for select to authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'provider_portfolio_items'
      and policyname = 'Providers can insert their own portfolio items'
  ) then
    create policy "Providers can insert their own portfolio items"
      on public.provider_portfolio_items
      for insert to authenticated
      with check (provider_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'provider_portfolio_items'
      and policyname = 'Providers can update their own portfolio items'
  ) then
    create policy "Providers can update their own portfolio items"
      on public.provider_portfolio_items
      for update to authenticated
      using (provider_user_id = auth.uid())
      with check (provider_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'provider_portfolio_items'
      and policyname = 'Providers can delete their own portfolio items'
  ) then
    create policy "Providers can delete their own portfolio items"
      on public.provider_portfolio_items
      for delete to authenticated
      using (provider_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'provider_portfolio_items'
      and policyname = 'Admins can manage portfolio items'
  ) then
    create policy "Admins can manage portfolio items"
      on public.provider_portfolio_items
      for all to authenticated
      using (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      )
      with check (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;
end
$$;

grant select, insert, update, delete on public.provider_portfolio_items to authenticated;

-- ============================================================
-- C. Storage bucket for provider portfolio images
-- ============================================================
insert into storage.buckets (id, name, public)
values ('provider-portfolio', 'provider-portfolio', false)
on conflict (id) do nothing;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Providers can upload their own portfolio files'
  ) then
    create policy "Providers can upload their own portfolio files"
      on storage.objects for insert to authenticated
      with check (
        bucket_id = 'provider-portfolio'
        and (storage.foldername(name))[1] = auth.uid()::text
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Providers can manage their own portfolio files'
  ) then
    create policy "Providers can manage their own portfolio files"
      on storage.objects for all to authenticated
      using (
        bucket_id = 'provider-portfolio'
        and (storage.foldername(name))[1] = auth.uid()::text
      )
      with check (
        bucket_id = 'provider-portfolio'
        and (storage.foldername(name))[1] = auth.uid()::text
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Authenticated users can view portfolio images'
  ) then
    create policy "Authenticated users can view portfolio images"
      on storage.objects for select to authenticated
      using (bucket_id = 'provider-portfolio');
  end if;
end
$$;
