-- NaijaFix: Riders
-- Idempotent: safe to run multiple times.
-- Preserves existing data.

-- ============================================================
-- A. Riders table
-- ============================================================
create table if not exists public.riders (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique,
  full_name text not null,
  phone text,
  vehicle_type text check (vehicle_type in ('motorcycle', 'bicycle', 'car', 'van')),
  vehicle_number text,
  active boolean not null default true,
  available boolean not null default true,
  current_latitude numeric(10, 7),
  current_longitude numeric(10, 7),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.riders enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'riders'
      and policyname = 'Riders can view their own profile'
  ) then
    create policy "Riders can view their own profile"
      on public.riders
      for select to authenticated
      using (user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'riders'
      and policyname = 'Riders can manage their own profile'
  ) then
    create policy "Riders can manage their own profile"
      on public.riders
      for all to authenticated
      using (user_id = auth.uid())
      with check (user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'riders'
      and policyname = 'Anyone can view active riders'
  ) then
    create policy "Anyone can view active riders"
      on public.riders
      for select to authenticated
      using (active = true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'riders'
      and policyname = 'Admins can manage all riders'
  ) then
    create policy "Admins can manage all riders"
      on public.riders
      for all to authenticated
      using (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      )
      with check (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;
end
$$;

create index if not exists idx_riders_user
  on public.riders (user_id);

create index if not exists idx_riders_available
  on public.riders (active, available);

grant select, insert, update, delete on public.riders to authenticated;
