-- NaijaFix Phase 2B-2 Step 2: Paystack webhook audit trail.
-- Additive only. No destructive operations. Does NOT modify the
-- completed Step 1 migration (20260916000000_phase2b2_payments.sql).
--
-- Records every inbound Paystack webhook event so the integration can
-- be audited and replayed. Writes are server-side only (service_role
-- via the Edge Function); authenticated users can never insert here.

create table if not exists public.payment_webhooks (
  id bigint generated by default as identity primary key,
  payment_id bigint references public.payments(id) on delete set null,
  paystack_reference text,
  event_type text,
  signature_valid boolean not null,
  payload jsonb not null,
  processed_at timestamptz not null default now()
);

alter table public.payment_webhooks enable row level security;

-- No broad policies. Reads are admin-only; writes are service_role.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'payment_webhooks'
      and policyname = 'Admins can view webhook audit'
  ) then
    create policy "Admins can view webhook audit"
      on public.payment_webhooks for select to authenticated
      using (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;
end
$$;

create index if not exists idx_payment_webhooks_reference
  on public.payment_webhooks (paystack_reference);

create index if not exists idx_payment_webhooks_payment
  on public.payment_webhooks (payment_id);

create index if not exists idx_payment_webhooks_processed
  on public.payment_webhooks (processed_at desc);

-- Idempotency: a given Paystack reference + event type should only be
-- recorded once. The table is new (no pre-existing rows), so the
-- partial unique index is safe to create without rewriting history.
create unique index if not exists payment_webhooks_reference_event_key
  on public.payment_webhooks (paystack_reference, event_type)
  where paystack_reference is not null and event_type is not null;
