-- NaijaFix: Food orders and order items
-- Idempotent: safe to run multiple times.
-- Preserves existing data.

-- ============================================================
-- A. Food orders
-- ============================================================
create table if not exists public.food_orders (
  id bigint generated by default as identity primary key,
  customer_user_id uuid not null,
  restaurant_id bigint not null references public.restaurants(id) on delete restrict,
  delivery_address text not null,
  delivery_latitude numeric(10, 7),
  delivery_longitude numeric(10, 7),
  subtotal numeric(10, 2) not null default 0,
  delivery_fee numeric(10, 2) not null default 0,
  total numeric(10, 2) not null default 0,
  status text not null default 'pending'
    check (status in ('pending', 'confirmed', 'preparing', 'ready_for_pickup', 'picked_up', 'out_for_delivery', 'delivered', 'cancelled')),
  payment_status text not null default 'pending'
    check (payment_status in ('pending', 'paid', 'failed', 'refunded')),
  rider_id bigint,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.food_orders enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'food_orders'
      and policyname = 'Customers can view their own orders'
  ) then
    create policy "Customers can view their own orders"
      on public.food_orders
      for select to authenticated
      using (customer_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'food_orders'
      and policyname = 'Customers can create their own orders'
  ) then
    create policy "Customers can create their own orders"
      on public.food_orders
      for insert to authenticated
      with check (customer_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'food_orders'
      and policyname = 'Customers can update their own pending orders'
  ) then
    create policy "Customers can update their own pending orders"
      on public.food_orders
      for update to authenticated
      using (customer_user_id = auth.uid() and status = 'pending')
      with check (customer_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'food_orders'
      and policyname = 'Restaurant owners can view orders for their restaurant'
  ) then
    create policy "Restaurant owners can view orders for their restaurant"
      on public.food_orders
      for select to authenticated
      using (
        exists (
          select 1 from public.restaurants r
          where r.id = restaurant_id and r.owner_user_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'food_orders'
      and policyname = 'Restaurant owners can update orders for their restaurant'
  ) then
    create policy "Restaurant owners can update orders for their restaurant"
      on public.food_orders
      for update to authenticated
      using (
        exists (
          select 1 from public.restaurants r
          where r.id = restaurant_id and r.owner_user_id = auth.uid()
        )
      )
      with check (
        exists (
          select 1 from public.restaurants r
          where r.id = restaurant_id and r.owner_user_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'food_orders'
      and policyname = 'Riders can view assigned deliveries'
  ) then
    create policy "Riders can view assigned deliveries"
      on public.food_orders
      for select to authenticated
      using (rider_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'food_orders'
      and policyname = 'Riders can update assigned delivery status'
  ) then
    create policy "Riders can update assigned delivery status"
      on public.food_orders
      for update to authenticated
      using (rider_id = auth.uid())
      with check (rider_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'food_orders'
      and policyname = 'Admins can manage all orders'
  ) then
    create policy "Admins can manage all orders"
      on public.food_orders
      for all to authenticated
      using (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      )
      with check (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;
end
$$;

create index if not exists idx_food_orders_customer
  on public.food_orders (customer_user_id, created_at desc);

create index if not exists idx_food_orders_restaurant
  on public.food_orders (restaurant_id, created_at desc);

create index if not exists idx_food_orders_status
  on public.food_orders (status);

create index if not exists idx_food_orders_rider
  on public.food_orders (rider_id);

grant select, insert, update on public.food_orders to authenticated;

-- ============================================================
-- B. Food order items
-- ============================================================
create table if not exists public.food_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.food_orders(id) on delete cascade,
  menu_item_id bigint references public.restaurant_menu_items(id) on delete set null,
  item_name_snapshot text not null,
  unit_price numeric(10, 2) not null,
  quantity integer not null check (quantity > 0),
  line_total numeric(10, 2) not null,
  created_at timestamptz not null default now()
);

alter table public.food_order_items enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'food_order_items'
      and policyname = 'Customers can view their own order items'
  ) then
    create policy "Customers can view their own order items"
      on public.food_order_items
      for select to authenticated
      using (
        exists (
          select 1 from public.food_orders fo
          where fo.id = order_id and fo.customer_user_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'food_order_items'
      and policyname = 'Restaurant owners can view order items for their restaurant'
  ) then
    create policy "Restaurant owners can view order items for their restaurant"
      on public.food_order_items
      for select to authenticated
      using (
        exists (
          select 1 from public.food_orders fo
          join public.restaurants r on r.id = fo.restaurant_id
          where fo.id = order_id and r.owner_user_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'food_order_items'
      and policyname = 'Customers can insert their own order items'
  ) then
    create policy "Customers can insert their own order items"
      on public.food_order_items
      for insert to authenticated
      with check (
        exists (
          select 1 from public.food_orders fo
          where fo.id = order_id and fo.customer_user_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'food_order_items'
      and policyname = 'Admins can manage all order items'
  ) then
    create policy "Admins can manage all order items"
      on public.food_order_items
      for all to authenticated
      using (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      )
      with check (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;
end
$$;

create index if not exists idx_food_order_items_order
  on public.food_order_items (order_id);

grant select, insert on public.food_order_items to authenticated;
