-- NaijaFix Phase 2B-2 Step 1: protected marketplace payments database foundation.

-- Additive only. No destructive operations. No existing tables, columns,
-- policies, or functions are dropped, renamed, or repurposed.

-- The existing bookings payment scaffolding columns
-- (payment_status, payment_authorized_at, payment_completed_at,
-- payment_failed_at, refund_pending_at, refunded_at) are intentionally left
-- untouched. They remain available as a denormalized read cache for the
-- existing admin queries and are NOT modified by this migration.

-- This migration creates:
--   1. public.payments - the authoritative payment ledger
--   2. RLS policies for public.payments
--   3. SECURITY DEFINER RPC foundation functions

-- No Paystack integration, no webhook handling, no payout/transfer logic,
-- and no frontend changes are included in this step. The RPCs below are
-- database-state machines only; they do not call any external payment API.

-- PAYMENT STATE MACHINE (enforced by the RPCs below):
--   unpaid   -> pending   (customer initiates)
--   pending  -> authorized (external capture confirmed)
--   pending  -> failed    (external capture failed)
--   failed   -> pending   (retry)
--   authorized -> captured (settlement recorded)
--   authorized -> released  (booking completed)
--   authorized -> refunded  (pre-completion refund)
--   released   -> refunded  (post-completion refund)

-- No other transition is permitted. A caller may never supply an arbitrary
-- status; every transition is validated inside the SECURITY DEFINER body.



-- ============================================================
-- A. public.payments - authoritative payment ledger
-- ============================================================
-- One row per payment attempt. booking_id is the FK to bookings(id);
-- customer_user_id and provider_user_id are denormalized from the
-- booking row so RLS can filter without a join back to bookings.
-- paystack_reference is UNIQUE so a duplicate webhook/confirm can never
-- insert a second row for the same payment.
-- idempotency_key is UNIQUE so a customer cannot submit two initiates
-- for the same logical payment attempt.
create table if not exists public.payments (
  id                    bigint generated by default as identity primary key,
  booking_id            bigint not null references public.bookings(id) on delete cascade,
  customer_user_id      uuid not null,
  provider_user_id      uuid,
  amount                numeric(12,2) not null check (amount > 0),
  currency              char(3) not null default 'NGN',
  paystack_reference    text,
  paystack_access_code  text,
  status                text not null default 'unpaid'
                          check (status in (
                            'unpaid', 'pending', 'authorized',
                            'captured', 'released', 'failed', 'refunded'
                          )),
  idempotency_key       text,
  commission_percent    numeric(5,2),
  provider_payout       numeric(12,2),
  platform_fee          numeric(12,2),
  authorized_at         timestamptz,
  captured_at           timestamptz,
  released_at           timestamptz,
  refunded_at           timestamptz,
  metadata              jsonb,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

-- paystack_reference is unique when present (NULL allowed pre-init).
create unique index if not exists payments_paystack_reference_key
  on public.payments (paystack_reference)
  where paystack_reference is not null;

-- idempotency_key is unique when present (NULL allowed pre-init).
create unique index if not exists payments_idempotency_key_key
  on public.payments (idempotency_key)
  where idempotency_key is not null;

create index if not exists idx_payments_booking
  on public.payments (booking_id);

create index if not exists idx_payments_customer
  on public.payments (customer_user_id);

create index if not exists idx_payments_provider
  on public.payments (provider_user_id);

create index if not exists idx_payments_status
  on public.payments (status);


-- updated_at trigger (mirrors the convention used by reviews/quotes).
create or replace function public.set_payments_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists payments_set_updated_at on public.payments;
create trigger payments_set_updated_at
  before update on public.payments
  for each row execute function public.set_payments_updated_at();


-- ============================================================
-- B. Enable RLS on public.payments
-- ============================================================
alter table public.payments enable row level security;

-- ============================================================
-- C. RLS policies for public.payments
-- ============================================================
-- Payments are sensitive financial records. Mutation is NEVER exposed
-- to authenticated users directly: every write happens through the
-- SECURITY DEFINER RPCs below, which run with elevated privileges and
-- enforce ownership/state transitions inside the function body.
-- These SELECT policies are intentionally narrow: a customer may only
-- read their own payments, a provider may only read payments where they
-- are the assigned provider, and admins may read everything.
-- No USING(true) / WITH CHECK(true) broad policies exist on this table.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'payments'
      and policyname = 'Customers can view their own payments'
  ) then
    create policy "Customers can view their own payments"
      on public.payments for select to authenticated
      using (customer_user_id = auth.uid());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'payments'
      and policyname = 'Providers can view their own payments'
  ) then
    create policy "Providers can view their own payments"
      on public.payments for select to authenticated
      using (
        provider_user_id is not null
        and provider_user_id = auth.uid()
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'payments'
      and policyname = 'Admins can view all payments'
  ) then
    create policy "Admins can view all payments"
      on public.payments for select to authenticated
      using (
        exists (
          select 1 from public.profiles p
          where p.user_id = auth.uid() and p.role = 'admin'
        )
      );
  end if;
end
$$;

-- ============================================================
-- D. Payment state-machine helper
-- ============================================================
-- Single source of truth for legal transitions. Adding a new state
-- requires updating BOTH this helper and the CHECK constraint above.
create or replace function public.payment_transition_allowed(
  p_from text,
  p_to text
)
returns boolean
language plpgsql
immutable
as $$
begin
  return (p_from, p_to) in (
    ('unpaid',   'pending'),
    ('pending',  'authorized'),
    ('pending',  'failed'),
    ('failed',   'pending'),
    ('authorized', 'captured'),
    ('authorized', 'released'),
    ('authorized', 'refunded'),
    ('released',   'refunded')
  );
end;
$$;

-- ============================================================
-- E. initiate_payment(p_booking_id, p_idempotency_key)
-- ============================================================
-- Database-side state machine ONLY. This function does NOT call any
-- external payment provider. It records the customer's intent to pay
-- and transitions unpaid -> pending. The actual Paystack initialize
-- call is performed by a server-side layer (Step 2) which then calls
-- confirm_payment() with the returned reference.
--
-- Security:
--   - SECURITY DEFINER so RLS cannot block the insert.
--   - SET search_path = '' and every reference is schema-qualified.
--   - Validates the caller is the booking's owning customer.
--   - Validates the booking exists and is in a pay-eligible state.
--   - Rejects duplicate idempotency keys (unique index).
--   - Rejects re-initiation of an already-paid booking.
create or replace function public.initiate_payment(
  p_booking_id bigint,
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_booking       public.bookings%rowtype;
  v_payment       public.payments%rowtype;
  v_provider_user_id uuid;
begin
  if p_booking_id is null then
    raise exception 'booking_id is required';
  end if;

  if p_idempotency_key is null or btrim(p_idempotency_key) = '' then
    raise exception 'idempotency_key is required';
  end if;

  -- Only the owning customer may initiate a payment.
  select * into v_booking
    from public.bookings b
   where b.id = p_booking_id;

  if not found then
    raise exception 'booking not found';
  end if;

  if v_booking.customer_user_id is null or v_booking.customer_user_id <> auth.uid() then
    raise exception 'forbidden';
  end if;

  -- A booking must be in a pay-eligible state (Accepted or later).
  if lower(coalesce(v_booking.status, '')) not in ('accepted', 'provider on the way', 'in progress', 'completed') then
    raise exception 'booking is not eligible for payment';
  end if;

  v_provider_user_id := v_booking.provider_user_id;

  -- Idempotency: if this key already exists, return the existing row.
  select * into v_payment
    from public.payments p
   where p.idempotency_key = p_idempotency_key;

  if found then
    return jsonb_build_object(
      'success', true,
      'payment_id', v_payment.id,
      'status', v_payment.status,
      'idempotent', true
    );
  end if;

  -- Insert a fresh payment row in the unpaid -> pending transition.
  insert into public.payments (
    booking_id,
    customer_user_id,
    provider_user_id,
    amount,
    currency,
    status,
    idempotency_key,
    metadata
  ) values (
    p_booking_id,
    auth.uid(),
    v_provider_user_id,
    0,
    'NGN',
    'pending',
    p_idempotency_key,
    jsonb_build_object('initiated_by', 'customer')
  )
  returning * into v_payment;

  return jsonb_build_object(
    'success', true,
    'payment_id', v_payment.id,
    'status', v_payment.status,
    'idempotency_key', v_payment.idempotency_key,
    'idempotent', false
  );
end;
$$;

-- Restricted EXECUTE: authenticated only. Function body enforces ownership.
revoke execute on function public.initiate_payment(bigint, text) from public;
revoke execute on function public.initiate_payment(bigint, text) from anon;
grant execute on function public.initiate_payment(bigint, text) to authenticated;

-- ============================================================
-- F. confirm_payment(p_booking_id, p_paystack_reference)
-- ============================================================
-- Database-side state machine ONLY. This function does NOT call any
-- external payment provider and does NOT verify a real Paystack
-- transaction. It records that an EXTERNAL capture was confirmed for
-- the booking's payment row and transitions pending -> authorized
-- (or pending -> failed when the external result was a failure).
--
-- The actual Paystack verification happens in a server-side layer
-- (Step 2) which calls this function AFTER it has verified the
-- transaction server-side. This function trusts nothing from the
-- caller about the external result except the explicit transition
-- requested, and it enforces the legal state machine.
--
-- Security:
--   - SECURITY DEFINER so the server-side layer (service_role) can
--     write even though authenticated users have no direct INSERT.
--   - Validates the booking exists and the payment row exists.
--   - Validates the paystack_reference matches the payment row.
--   - Rejects any transition not permitted by the state machine.
--   - Idempotent: re-confirming an already-authorized row is a no-op.
create or replace function public.confirm_payment(
  p_booking_id bigint,
  p_paystack_reference text,
  p_authorized boolean
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_payment public.payments%rowtype;
  v_new_status text;
begin
  if p_booking_id is null then
    raise exception 'booking_id is required';
  end if;

  if p_paystack_reference is null or btrim(p_paystack_reference) = '' then
    raise exception 'paystack_reference is required';
  end if;

  select * into v_payment
    from public.payments p
   where p.booking_id = p_booking_id
     and p.paystack_reference = p_paystack_reference;

  if not found then
    raise exception 'payment not found for this booking and reference';
  end if;

  if v_payment.status = 'authorized' or v_payment.status = 'captured'
     or v_payment.status = 'released' then
    return jsonb_build_object(
      'success', true,
      'payment_id', v_payment.id,
      'status', v_payment.status,
      'idempotent', true
    );
  end if;

  v_new_status := case when p_authorized then 'authorized' else 'failed' end;

  if not public.payment_transition_allowed(v_payment.status, v_new_status) then
    raise exception 'invalid payment transition from % to %', v_payment.status, v_new_status;
  end if;

  update public.payments p
     set status = v_new_status,
         paystack_reference = p_paystack_reference,
         authorized_at = case when v_new_status = 'authorized' then now() else v_payment.authorized_at end,
         captured_at   = case when v_new_status = 'failed' then now() else v_payment.captured_at end,
         metadata = coalesce(v_payment.metadata, '{}'::jsonb) || jsonb_build_object('confirmed_at', now())
   where p.id = v_payment.id
  returning * into v_payment;

  return jsonb_build_object(
    'success', true,
    'payment_id', v_payment.id,
    'status', v_payment.status,
    'idempotent', false
  );
end;
$$;

-- Restricted EXECUTE: service_role ONLY.
-- confirm_payment() represents an EXTERNAL payment event (Paystack capture
-- confirmed), NOT a user action. It transitions pending -> authorized or
-- pending -> failed. Granting it to authenticated would let any logged-in
-- user claim "my payment was captured" without completing checkout.
-- The server-side verification/webhook layer runs as service_role, which
-- bypasses GRANT checks and is the ONLY caller permitted here.
revoke execute on function public.confirm_payment(bigint, text, boolean) from public;
revoke execute on function public.confirm_payment(bigint, text, boolean) from anon;
revoke execute on function public.confirm_payment(bigint, text, boolean) from authenticated;

-- ============================================================
-- G. release_payment(p_booking_id)
-- ============================================================
-- Database-side state machine ONLY. This function does NOT call any
-- external payment provider and does NOT issue a Paystack transfer.
-- It records that the provider's payout has been RELEASED and
-- transitions authorized -> released (or captured -> released).
--
-- Intentional limitation for Step 1: this function does NOT compute
-- commission or issue a real payout. Those are server-side concerns
-- (Step 2/3). The function only validates the state machine and
-- records the release timestamp. Commission math and the Paystack
-- transfer call are intentionally deferred so this migration can
-- never move real money.
--
-- Security:
--   - SECURITY DEFINER so the server-side layer can write.
--   - Validates the booking and payment exist.
--   - Validates the caller is EITHER the assigned provider OR an
--     admin. A customer can never release a payment.
--   - Rejects any transition not permitted by the state machine.
--   - Idempotent: releasing an already-released row is a no-op.
create or replace function public.release_payment(p_booking_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_payment public.payments%rowtype;
  v_is_provider boolean := false;
  v_is_admin boolean := false;
begin
  if p_booking_id is null then
    raise exception 'booking_id is required';
  end if;

  select * into v_payment
    from public.payments p
   where p.booking_id = p_booking_id;

  if not found then
    raise exception 'payment not found for this booking';
  end if;

  if v_payment.status = 'released' then
    return jsonb_build_object(
      'success', true,
      'payment_id', v_payment.id,
      'status', v_payment.status,
      'idempotent', true
    );
  end if;

  if v_payment.status not in ('authorized', 'captured') then
    raise exception 'payment cannot be released in status %', v_payment.status;
  end if;

  -- Only the assigned provider or an admin may release a payment.
  if v_payment.provider_user_id is not null and v_payment.provider_user_id = auth.uid() then
    v_is_provider := true;
  end if;

  if exists (
    select 1 from public.profiles pr
    where pr.user_id = auth.uid() and pr.role = 'admin'
  ) then
    v_is_admin := true;
  end if;

  if not (v_is_provider or v_is_admin) then
    raise exception 'forbidden: only the assigned provider or an admin may release a payment';
  end if;

  update public.payments p
     set status = 'released',
         released_at = now(),
         metadata = coalesce(v_payment.metadata, '{}'::jsonb) || jsonb_build_object('released_at', now(), 'released_by', auth.uid())
   where p.id = v_payment.id
  returning * into v_payment;

  return jsonb_build_object(
    'success', true,
    'payment_id', v_payment.id,
    'status', v_payment.status,
    'released_at', v_payment.released_at,
    'idempotent', false
  );
end;
$$;

-- Restricted EXECUTE: service_role ONLY.
-- release_payment() represents an EXTERNAL payout event (provider release),
-- NOT a user action. It transitions authorized/captured -> released.
-- Granting it to authenticated would let any logged-in user release a
-- payment. The server-side payout layer runs as service_role, which
-- bypasses GRANT checks and is the ONLY caller permitted here.
revoke execute on function public.release_payment(bigint) from public;
revoke execute on function public.release_payment(bigint) from anon;
revoke execute on function public.release_payment(bigint) from authenticated;

-- ============================================================
-- H. refund_payment(p_booking_id, p_reason)
-- ============================================================
-- Database-side state machine ONLY. This function does NOT call any
-- external payment provider and does NOT issue a Paystack refund.
-- It records that a refund has been approved and transitions
-- authorized -> refunded or released -> refunded.
--
-- Intentional limitation for Step 1: the actual Paystack refund call
-- is a server-side concern (Step 2/3) and is intentionally deferred so
-- this migration can never move real money.
--
-- Security:
--   - SECURITY DEFINER so the server-side layer can write.
--   - Validates the booking and payment exist.
--   - Validates the caller is the owning customer OR an admin. A
--     provider can never refund a customer's payment.
--   - Rejects any transition not permitted by the state machine.
--   - Idempotent: refunding an already-refunded row is a no-op.
create or replace function public.refund_payment(
  p_booking_id bigint,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_payment public.payments%rowtype;
  v_is_admin boolean := false;
begin
  if p_booking_id is null then
    raise exception 'booking_id is required';
  end if;

  select * into v_payment
    from public.payments p
   where p.booking_id = p_booking_id;

  if not found then
    raise exception 'payment not found for this booking';
  end if;

  if v_payment.status = 'refunded' then
    return jsonb_build_object(
      'success', true,
      'payment_id', v_payment.id,
      'status', v_payment.status,
      'idempotent', true
    );
  end if;

  if v_payment.status not in ('authorized', 'released') then
    raise exception 'payment cannot be refunded in status %', v_payment.status;
  end if;

  -- Only the owning customer or an admin may request a refund.
  if v_payment.customer_user_id <> auth.uid() then
    if exists (
      select 1 from public.profiles pr
      where pr.user_id = auth.uid() and pr.role = 'admin'
    ) then
      v_is_admin := true;
    else
      raise exception 'forbidden: only the customer who paid or an admin may refund';
    end if;
  end if;

  update public.payments p
     set status = 'refunded',
         refunded_at = now(),
         metadata = coalesce(v_payment.metadata, '{}'::jsonb)
                || jsonb_build_object('refunded_at', now(), 'refunded_by', auth.uid(), 'reason', p_reason)
   where p.id = v_payment.id
  returning * into v_payment;

  return jsonb_build_object(
    'success', true,
    'payment_id', v_payment.id,
    'status', v_payment.status,
    'refunded_at', v_payment.refunded_at,
    'idempotent', false
  );
end;
$$;

-- Restricted EXECUTE: authenticated only. Function body enforces
-- customer/admin authorization.
revoke execute on function public.refund_payment(bigint, text) from public;
revoke execute on function public.refund_payment(bigint, text) from anon;
grant execute on function public.refund_payment(bigint, text) to authenticated;

-- ============================================================
-- J. initialize_payment_reference(p_payment_id, p_paystack_reference, p_paystack_access_code)
-- ============================================================
-- Attaches the Paystack reference/access code to an existing payment
-- that is in the 'pending' state, WITHOUT changing its status.
--
-- This is the ONLY safe privileged path for the server-side init
-- layer to record the Paystack reference after /transaction/initialize.
--
-- It does NOT:
--   - change pending -> authorized (that is confirm_payment's job)
--   - change amount, customer_user_id, provider_user_id, or booking_id
--   - accept a client-provided customer/provider identity
--   - allow re-attaching a different reference to the same payment
--   - allow the same reference to be attached to two payments
--
-- Security:
--   - SECURITY DEFINER so the server-side layer can write despite RLS.
--   - SET search_path = '' and every reference is schema-qualified.
--   - service_role ONLY: no authenticated/anon caller may attach a
--     reference, so a customer cannot forge a Paystack reference.
--   - Validates the payment exists and is in 'pending'.
--   - Validates the payment has no reference yet (rejects overwrite).
--   - Validates the new reference is not already used by another payment.
--   - Idempotent: re-calling with the same reference is a no-op.
create or replace function public.initialize_payment_reference(
  p_payment_id bigint,
  p_paystack_reference text,
  p_paystack_access_code text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_payment public.payments%rowtype;
  v_existing public.payments%rowtype;
begin
  if p_payment_id is null then
    raise exception 'payment_id is required';
  end if;

  if p_paystack_reference is null or btrim(p_paystack_reference) = '' then
    raise exception 'paystack_reference is required';
  end if;

  select * into v_payment
    from public.payments p
   where p.id = p_payment_id;

  if not found then
    raise exception 'payment not found';
  end if;

  if v_payment.status <> 'pending' then
    raise exception 'payment must be in pending state to attach a reference, currently %', v_payment.status;
  end if;

  if v_payment.paystack_reference is not null then
    -- Idempotent: same reference on the same payment is a no-op.
    if v_payment.paystack_reference = p_paystack_reference then
      return jsonb_build_object(
        'success', true,
        'payment_id', v_payment.id,
        'paystack_reference', v_payment.paystack_reference,
        'paystack_access_code', v_payment.paystack_access_code,
        'status', v_payment.status,
        'idempotent', true
      );
    end if;
    raise exception 'payment already has a reference: %', v_payment.paystack_reference;
  end if;

  -- Reject a reference already attached to a different payment.
  select * into v_existing
    from public.payments p
   where p.paystack_reference = p_paystack_reference;

  if found then
    raise exception 'paystack_reference already in use by payment %', v_existing.id;
  end if;

  update public.payments p
     set paystack_reference = p_paystack_reference,
         paystack_access_code = p_paystack_access_code,
         metadata = coalesce(v_payment.metadata, '{}'::jsonb)
                || jsonb_build_object(
                     'paystack_initialized_at', now(),
                     'paystack_reference', p_paystack_reference
                   )
   where p.id = v_payment.id
  returning * into v_payment;

  return jsonb_build_object(
    'success', true,
    'payment_id', v_payment.id,
    'paystack_reference', v_payment.paystack_reference,
    'paystack_access_code', v_payment.paystack_access_code,
    'status', v_payment.status,
    'idempotent', false
  );
end;
$$;

-- Restricted EXECUTE: service_role ONLY.
-- Attaching a Paystack reference is a privileged server-side operation.
-- Granting it to authenticated would let any logged-in user forge a
-- reference on any payment. The server-side init layer runs as
-- service_role, which bypasses GRANT checks and is the ONLY caller
-- permitted here.
revoke execute on function public.initialize_payment_reference(bigint, text, text) from public;
revoke execute on function public.initialize_payment_reference(bigint, text, text) from anon;
revoke execute on function public.initialize_payment_reference(bigint, text, text) from authenticated;

-- ============================================================
-- I. Grants (RLS remains authoritative)
-- ============================================================
grant select on public.payments to authenticated;
